export type Lang = 'pt' | 'en';

const pt = {
  appName: 'Portify',
  tagline: 'Gestão de património inteligente e simplificada.',
  // Auth
  loginTitle: 'Bem-vindo de volta',
  loginSubtitle: 'Inicie sessão para gerir o seu património.',
  emailLabel: 'Email',
  emailPh: 'nome@exemplo.com',
  passwordLabel: 'Palavra-passe',
  passwordPh: '••••••••',
  forgotPassword: 'Esqueceu-se da palavra-passe?',
  signIn: 'Entrar',
  faceId: 'Entrar com Face ID',
  noAccount: 'Não tem conta?',
  createAccount: 'Criar conta',
  rememberMe: 'Manter sessão iniciada',
  orContinue: 'ou continue com',
  // Register
  registerTitle: 'Criar a sua conta',
  registerSubtitle: 'Comece a investir em poucos minutos.',
  regFirstName: 'Primeiro Nome',
  regLastName: 'Último Nome',
  firstNamePh: 'Ricardo',
  lastNamePh: 'Ferreira',
  regDob: 'Data de Nascimento',
  regDobPh: 'DD / MM / AAAA',
  regUserId: 'ID de Utilizador',
  regUserIdPh: '@ricardo.f',
  confirmPasswordLabel: 'Confirmar palavra-passe',
  acceptTerms: 'Aceito os',
  terms: 'Termos',
  and: 'e a',
  privacy: 'Política de Privacidade',
  haveAccount: 'Já tem conta?',
  // PIN
  pinTitle: 'Introduza o PIN',
  pinSub: 'Use o código de 6 dígitos para entrar',
  forgotPin: 'Esqueci o PIN',
  // Onboarding
  onbSteps: [
    { icon: 'monitoring', title: 'Todo o seu património num só lugar', text: 'Acompanhe ações, ETFs e cripto com dados de mercado em tempo real.' },
    { icon: 'donut_small', title: 'Decisões com clareza', text: 'Visualize a alocação por setor e a performance com gráficos simples e precisos.' },
    { icon: 'lock', title: 'Seguro e privado', text: 'Acesso biométrico e encriptação de ponta a ponta protegem os seus dados.' },
  ],
  skip: 'Saltar',
  next: 'Seguinte',
  start: 'Começar',
  // Navigation
  navDash: 'Painel',
  navPort: 'Portfólio',
  navFor: 'Para Si',
  navProfile: 'Perfil',
  navTx: 'Movim.',
  // Dashboard
  greeting: 'Olá, Ricardo',
  totalValue: 'Valor Total do Portfólio',
  dailyPerf: 'Performance Diária',
  allocation: 'Alocação por Setor',
  tech: 'Tecnologia',
  energy: 'Energia',
  health: 'Saúde',
  others: 'Outros',
  assets: '12 Ativos',
  markets: 'MERCADOS',
  newsTitle: 'BCE sinaliza manutenção de taxas: o que esperar para o seu portfólio?',
  readMore: 'Ler mais em 3 min',
  // Portfolio
  positions: 'Posições',
  dividends: 'Dividendos',
  history: 'Histórico',
  position: 'Posição',
  units: 'Unid.',
  avgPrice: 'Preço Médio',
  currentValue: 'Valor Atual',
  totalGain: 'Ganho Total',
  totalLoss: 'Perda Total',
  addAsset: 'Adicionar',
  buy: 'Comprar',
  sell: 'Vender',
  // Profile
  investorSince: 'Investidor desde 2018',
  risk: 'Risco',
  moderate: 'Moderado',
  objective: 'Objetivo',
  retirement: 'Reforma',
  accountPlanning: 'Conta e Planeamento',
  personalData: 'Dados Pessoais',
  investmentPlan: 'Plano de Investimento',
  monthly: 'Mensal: € 1.200,00',
  preferences: 'Preferências',
  darkTheme: 'Tema Escuro',
  language: 'Idioma',
  langValue: 'Português (PT)',
  currency: 'Moeda Principal',
  dataManagement: 'Gestão de Dados',
  importPortfolio: 'Importar Portfólio',
  importFormats: 'CSV, XLSX, Google Sheets',
  exportReport: 'Exportar Relatório',
  annualPdf: 'Relatório Anual em PDF',
  signOut: 'Terminar Sessão',
  back: 'Voltar',
  save: 'Guardar',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
};

const en: typeof pt = {
  appName: 'Portify',
  tagline: 'Smart, simplified wealth management.',
  loginTitle: 'Welcome back',
  loginSubtitle: 'Sign in to manage your wealth.',
  emailLabel: 'Email',
  emailPh: 'name@example.com',
  passwordLabel: 'Password',
  passwordPh: '••••••••',
  forgotPassword: 'Forgot your password?',
  signIn: 'Sign in',
  faceId: 'Sign in with Face ID',
  noAccount: 'No account?',
  createAccount: 'Create account',
  rememberMe: 'Keep me signed in',
  orContinue: 'or continue with',
  registerTitle: 'Create your account',
  registerSubtitle: 'Start investing in just a few minutes.',
  regFirstName: 'First Name',
  regLastName: 'Last Name',
  firstNamePh: 'Ricardo',
  lastNamePh: 'Ferreira',
  regDob: 'Date of Birth',
  regDobPh: 'DD / MM / YYYY',
  regUserId: 'User ID',
  regUserIdPh: '@ricardo.f',
  confirmPasswordLabel: 'Confirm password',
  acceptTerms: 'I accept the',
  terms: 'Terms',
  and: 'and',
  privacy: 'Privacy Policy',
  haveAccount: 'Already have an account?',
  pinTitle: 'Enter PIN',
  pinSub: 'Use your 6-digit code to sign in',
  forgotPin: 'Forgot PIN',
  onbSteps: [
    { icon: 'monitoring', title: 'All your wealth in one place', text: 'Track stocks, ETFs and crypto with real-time market data.' },
    { icon: 'donut_small', title: 'Make decisions with clarity', text: 'Visualize sector allocation and performance with simple, accurate charts.' },
    { icon: 'lock', title: 'Secure and private', text: 'Biometric access and end-to-end encryption protect your data.' },
  ],
  skip: 'Skip',
  next: 'Next',
  start: 'Get started',
  navDash: 'Dashboard',
  navPort: 'Portfolio',
  navFor: 'For You',
  navProfile: 'Profile',
  navTx: 'Activity',
  greeting: 'Hi, Ricardo',
  totalValue: 'Total Portfolio Value',
  dailyPerf: 'Daily Performance',
  allocation: 'Allocation by Sector',
  tech: 'Technology',
  energy: 'Energy',
  health: 'Healthcare',
  others: 'Others',
  assets: '12 Assets',
  markets: 'MARKETS',
  newsTitle: 'ECB signals rate hold: what it means for your portfolio?',
  readMore: '3 min read',
  positions: 'Holdings',
  dividends: 'Dividends',
  history: 'History',
  position: 'Position',
  units: 'Units',
  avgPrice: 'Avg. Price',
  currentValue: 'Current Value',
  totalGain: 'Total Gain',
  totalLoss: 'Total Loss',
  addAsset: 'Add',
  buy: 'Buy',
  sell: 'Sell',
  investorSince: 'Investor since 2018',
  risk: 'Risk',
  moderate: 'Moderate',
  objective: 'Goal',
  retirement: 'Retirement',
  accountPlanning: 'Account & Planning',
  personalData: 'Personal Data',
  investmentPlan: 'Investment Plan',
  monthly: 'Monthly: € 1,200.00',
  preferences: 'Preferences',
  darkTheme: 'Dark Theme',
  language: 'Language',
  langValue: 'English (EN)',
  currency: 'Main Currency',
  dataManagement: 'Data Management',
  importPortfolio: 'Import Portfolio',
  importFormats: 'CSV, XLSX, Google Sheets',
  exportReport: 'Export Report',
  annualPdf: 'Annual Report in PDF',
  signOut: 'Sign Out',
  back: 'Back',
  save: 'Save',
  confirm: 'Confirm',
  cancel: 'Cancel',
};

export function useDict(lang: Lang) {
  return lang === 'pt' ? pt : en;
}

export type Dict = typeof pt;
