import type { pt } from './pt';

export const en: typeof pt = {
  appName: 'Portify',
  tagline: 'Smart, simplified wealth management.',
  loginTitle: 'Welcome back',
  loginSubtitle: 'Sign in to manage your wealth.',
  emailLabel: 'Email',
  emailPh: 'name@example.com',
  passwordLabel: 'Password',
  passwordPh: '••••••••',
  forgotPassword: 'Forgot your password?',
  signIn: 'Sign in',
  faceId: 'Sign in with Face ID',
  noAccount: 'No account?',
  createAccount: 'Create account',
  rememberMe: 'Keep me signed in',
  orContinue: 'or continue with',
  registerTitle: 'Create your account',
  registerSubtitle: 'Start investing in just a few minutes.',
  regFirstName: 'First Name',
  regLastName: 'Last Name',
  firstNamePh: 'Ricardo',
  lastNamePh: 'Ferreira',
  regDob: 'Date of Birth',
  regDobPh: 'DD / MM / YYYY',
  regUserId: 'User ID',
  regUserIdPh: '@ricardo.f',
  confirmPasswordLabel: 'Confirm password',
  acceptTerms: 'I accept the',
  terms: 'Terms',
  and: 'and',
  privacy: 'Privacy Policy',
  haveAccount: 'Already have an account?',
  pinTitle: 'Enter PIN',
  pinSub: 'Use your 6-digit code to sign in',
  forgotPin: 'Forgot PIN',
  onbSteps: [
    { icon: 'monitoring', title: 'All your wealth in one place', text: 'Track stocks, ETFs and crypto with real-time market data.' },
    { icon: 'donut_small', title: 'Make decisions with clarity', text: 'Visualize sector allocation and performance with simple, accurate charts.' },
    { icon: 'lock', title: 'Secure and private', text: 'Biometric access and end-to-end encryption protect your data.' },
  ],
  skip: 'Skip',
  next: 'Next',
  start: 'Get started',
  navDash: 'Dashboard',
  navPort: 'Portfolio',
  navFor: 'For You',
  navProfile: 'Profile',
  navTx: 'Activity',
  greeting: 'Hi, Ricardo',
  totalValue: 'Total Portfolio Value',
  dailyPerf: 'Daily Performance',
  allocation: 'Allocation by Sector',
  tech: 'Technology',
  energy: 'Energy',
  health: 'Healthcare',
  others: 'Others',
  assets: '12 Assets',
  markets: 'MARKETS',
  newsTitle: 'ECB signals rate hold: what it means for your portfolio?',
  readMore: '3 min read',
  positions: 'Holdings',
  dividends: 'Dividends',
  history: 'History',
  position: 'Position',
  units: 'Units',
  avgPrice: 'Avg. Price',
  currentValue: 'Current Value',
  totalGain: 'Total Gain',
  totalLoss: 'Total Loss',
  addAsset: 'Add',
  buy: 'Buy',
  sell: 'Sell',
  investorSince: 'Investor since 2018',
  risk: 'Risk',
  moderate: 'Moderate',
  objective: 'Goal',
  retirement: 'Retirement',
  accountPlanning: 'Account & Planning',
  personalData: 'Personal Data',
  investmentPlan: 'Investment Plan',
  monthly: 'Monthly: € 1,200.00',
  preferences: 'Preferences',
  darkTheme: 'Dark Theme',
  language: 'Language',
  langValue: 'English (EN)',
  currency: 'Main Currency',
  dataManagement: 'Data Management',
  importPortfolio: 'Import Portfolio',
  importFormats: 'CSV, XLSX, Google Sheets',
  exportReport: 'Export Report',
  annualPdf: 'Annual Report in PDF',
  signOut: 'Sign Out',
  back: 'Back',
  save: 'Save',
  confirm: 'Confirm',
  cancel: 'Cancel',
  // Profile page
  profileTitle: 'Profile',
  memberSince: 'Member since 2024',
  investorProfileSection: 'Investor profile',
  riskProfileLabel: 'Risk profile',
  horizonLabel: 'Time horizon',
  horizonValue: '5–10 years',
  sectorsLabel: 'Sectors',
  sectorsValue: 'Tech, Healthcare',
  investmentPlanSection: 'Investment plan',
  activePlan: 'Active plan',
  planValue: '€250/Monthly',
  portfolioSection: 'Portfolio',
  importCsv: 'Import CSV',
  importAction: 'Import',
  exportData: 'Export data',
  linkBroker: 'Link broker',
  accountSection: 'Account',
  security: 'Security',
  settingsLabel: 'Settings',
  longTermGoal: 'Long term',
};
