import type { pt } from './pt';

export const en: typeof pt = {
  appName: 'Portify',
  tagline: 'Smart, simplified wealth management.',
  txcBuy: 'Buy',
  txcSell: 'Sell',
  txcDiv: 'Dividend',
  txcUnits: 'Units',
  txcUnitVal: 'Unit price',
  txcDelete: 'Delete',
  noTransactions: 'No transactions yet.',
  loginTitle: 'Welcome back',
  loginSubtitle: 'Sign in to manage your wealth.',
  emailLabel: 'Email',
  emailPh: 'name@example.com',
  passwordLabel: 'Password',
  passwordPh: '••••••••',
  forgotPassword: 'Forgot your password?',
  signIn: 'Sign in',
  faceId: 'Sign in with Face ID',
  noAccount: 'No account?',
  createAccount: 'Create account',
  rememberMe: 'Keep me signed in',
  orContinue: 'or continue with',
  registerTitle: 'Create your account',
  registerSubtitle: 'Start investing in just a few minutes.',
  regFirstName: 'First Name',
  regLastName: 'Last Name',
  firstNamePh: 'Ricardo',
  lastNamePh: 'Ferreira',
  regDob: 'Date of Birth',
  regDobPh: 'DD / MM / YYYY',
  regUserId: 'User ID',
  regUserIdPh: '@ricardo.f',
  confirmPasswordLabel: 'Confirm password',
  acceptTerms: 'I accept the',
  terms: 'Terms',
  and: 'and',
  privacy: 'Privacy Policy',
  haveAccount: 'Already have an account?',
  pinTitle: 'Enter PIN',
  pinSub: 'Use your 6-digit code to sign in',
  forgotPin: 'Forgot PIN',
  pinWrong: 'Incorrect PIN. Try again.',
  onbSteps: [
    { icon: 'monitoring', title: 'All your wealth in one place', text: 'Track stocks, ETFs and crypto with real-time market data.' },
    { icon: 'donut_small', title: 'Make decisions with clarity', text: 'Visualize sector allocation and performance with simple, accurate charts.' },
    { icon: 'lock', title: 'Secure and private', text: 'Biometric access and end-to-end encryption protect your data.' },
  ],
  skip: 'Skip',
  next: 'Next',
  start: 'Get started',
  navDash: 'Dashboard',
  navPort: 'Portfolio',
  navFor: 'For You',
  navProfile: 'Profile',
  navTx: 'Activity',
  greeting: 'Hi, Ricardo',
  totalValue: 'Total Portfolio Value',
  patPortfolioSummary: 'Portfolio Summary',
  dayChange: 'Today',
  investedLabel: 'Invested',
  returnLabel: 'Return',
  dailyPerf: 'Daily Performance',
  allocation: 'Allocation by Sector',
  tech: 'Technology',
  energy: 'Energy',
  health: 'Healthcare',
  others: 'Others',
  assets: '12 Assets',
  markets: 'MARKETS',
  newsTitle: 'ECB signals rate hold: what it means for your portfolio?',
  readMore: '3 min read',
  insightDivTitle: '3 dividends this week',
  insightDivSub: 'AAPL, MSFT and KO pay in the next few days.',
  insightPlanTitle: 'Auto top-up active',
  insightPlanSub: '250 € will be invested on the 1st each month.',
  positions: 'Holdings',
  dividends: 'Dividends',
  history: 'History',
  position: 'Position',
  units: 'Units',
  avgPrice: 'Avg. Price',
  detailStats: 'Statistics',
  detailAbout: 'About',
  detailAboutName: 'Name',
  detailAboutSector: 'Sector',
  detailAboutExchange: 'Exchange',
  detailNoInfo: 'No information available.',
  detailNoQuote: 'Quote unavailable for this asset.',
  open: 'Open',
  prevClose: 'Prev. close',
  dayHigh: 'Day high',
  dayLow: 'Day low',
  currentValue: 'Current Value',
  totalGain: 'Total Gain',
  totalLoss: 'Total Loss',
  addAsset: 'Add',
  buy: 'Buy',
  sell: 'Sell',
  bsBuyTitle: 'Record purchase',
  bsSellTitle: 'Record sale',
  bsShares: 'Shares',
  bsAvgPrice: 'Avg. price (€)',
  bsDate: 'Date',
  bsTime: 'Time',
  bsConfirm: 'Confirm purchase',
  bsSellConfirm: 'Confirm sale',
  bsError: 'Enter the number of shares and the average price.',
  investorSince: 'Investor since 2018',
  risk: 'Risk',
  moderate: 'Moderate',
  objective: 'Goal',
  retirement: 'Retirement',
  accountPlanning: 'Account & Planning',
  personalData: 'Personal Data',
  pdTitle: 'Personal data',
  pdFirstName: 'First name',
  pdLastName: 'Last name',
  pdDob: 'Date of birth',
  pdUserId: 'User ID',
  pdEmailLabel: 'Email',
  pdLocked: 'locked',
  pdEmailSaved: 'Email updated.',
  pdEmailError: 'Could not update email.',
  impTitle: 'Import Portfolio',
  impSub: 'Upload a CSV or XLSX file with your positions.',
  impDrop: 'Drag a file or tap to browse',
  impDropHint: 'CSV, XLSX · ticker, units, avg price',
  impCancel: 'Cancel',
  impConfirm: 'Import',
  impImporting: 'Importing...',
  impToastTitle: 'Portfolio imported',
  impToastSub: 'Your positions have been updated.',
  impNoFile: 'Choose a CSV or XLSX file first.',
  impParseError: 'Could not read the file. Check the format (CSV or XLSX).',
  exportTitle: 'Export Portfolio',
  exportDesc: 'Export your full transaction history and positions.',
  format: 'Format',
  exportCsv: 'CSV',
  exportPdf: 'PDF',
  period: 'Period',
  periodAllTime: 'All time',
  periodThisYear: 'This year',
  periodLast12: 'Last 12 months',
  periodCustom: 'Custom',
  exportStartLabel: 'Start date',
  exportEndLabel: 'End date',
  exportToastTitle: 'Export complete',
  exportToastSub: 'Your file has been downloaded.',
  download: 'Download',
  investmentPlan: 'Investment Plan',
  monthly: 'Monthly: € 1,200.00',
  preferences: 'Preferences',
  darkTheme: 'Dark Theme',
  language: 'Language',
  langValue: 'English (EN)',
  currency: 'Main Currency',
  dataManagement: 'Data Management',
  importPortfolio: 'Import Portfolio',
  importFormats: 'CSV, XLSX, Google Sheets',
  exportReport: 'Export Report',
  annualPdf: 'Annual Report in PDF',
  signOut: 'Sign Out',
  back: 'Back',
  save: 'Save',
  confirm: 'Confirm',
  cancel: 'Cancel',
  // Profile page
  profileTitle: 'Profile',
  memberSince: 'Member since 2024',
  investorProfileSection: 'Investor profile',
  riskProfileLabel: 'Risk profile',
  horizonLabel: 'Time horizon',
  horizonValue: '5–10 years',
  sectorsLabel: 'Sectors',
  sectorsValue: 'Tech, Healthcare',
  investmentPlanSection: 'Investment plan',
  activePlan: 'Active plan',
  planValue: '€250/Monthly',
  portfolioSection: 'Portfolio',
  importCsv: 'Import Portfolio',
  importAction: 'Import',
  exportData: 'Export data',
  linkBroker: 'Link broker',
  accountSection: 'Account',
  security: 'Security',
  settingsLabel: 'Settings',
  longTermGoal: 'Long term',
};
