export const pt = {
  appName: 'Portify',
  tagline: 'Gestão de património inteligente e simplificada.',
  txcBuy: 'Compra',
  txcSell: 'Venda',
  txcDiv: 'Dividendo',
  txcDeposit: 'Depósito',
  txcInterest: 'Juros',
  txcWht: 'Retenção (WHT)',
  txcInterestTax: 'Imposto s/ juros',
  freeFundsSection: 'Fundos livres',
  uninvestedCashLabel: 'Saldo não investido',
  freeFundsRateLabel: 'Taxa de juro anual',
  lowConfidence: 'baixa confiança',
  grossLabel: 'bruto',
  txcUnits: 'Unidades',
  txcUnitVal: 'Valor unit.',
  txcDelete: 'Apagar',
  noTransactions: 'Sem movimentos registados.',
  noFilteredTransactions: 'Nenhum movimento corresponde ao filtro.',
  historyDateFrom: 'De',
  historyDateTo: 'Até',
  // Auth
  loginTitle: 'Bem-vindo de volta',
  loginSubtitle: 'Inicie sessão para gerir o seu património.',
  loginIdLabel: 'ID de utilizador',
  loginIdPh: 'o_teu_username',
  emailLabel: 'Email',
  emailPh: 'nome@exemplo.com',
  passwordLabel: 'Palavra-passe',
  passwordPh: '••••••••',
  forgotPassword: 'Esqueceu-se da palavra-passe?',
  signIn: 'Entrar',
  faceId: 'Entrar com Face ID',
  noAccount: 'Não tem conta?',
  createAccount: 'Criar conta',
  rememberMe: 'Manter sessão iniciada',
  orContinue: 'ou continue com',
  // Register
  registerTitle: 'Criar a sua conta',
  registerSubtitle: 'Comece a investir em poucos minutos.',
  regFirstName: 'Primeiro Nome',
  regLastName: 'Sobrenome',
  firstNamePh: 'Ricardo',
  lastNamePh: 'Ferreira',
  regDob: 'Data de Nascimento',
  regDobPh: 'DD / MM / AAAA',
  regUserId: 'ID de Utilizador',
  regUserIdPh: '@ricardo.f',
  confirmPasswordLabel: 'Confirmar palavra-passe',
  acceptTerms: 'Aceito os',
  terms: 'Termos',
  and: 'e a',
  privacy: 'Política de Privacidade',
  haveAccount: 'Já tem conta?',
  // PIN
  pinTitle: 'Introduza o PIN',
  pinSub: 'Use o código de 6 dígitos para entrar',
  forgotPin: 'Esqueci o PIN',
  pinWrong: 'PIN incorreto. Tenta de novo.',
  // Onboarding
  onbSteps: [
    { icon: 'monitoring', title: 'Todo o seu património num só lugar', text: 'Acompanhe ações, ETFs e cripto com dados de mercado em tempo real.' },
    { icon: 'donut_small', title: 'Decisões com clareza', text: 'Visualize a alocação por setor e a performance com gráficos simples e precisos.' },
    { icon: 'lock', title: 'Seguro e privado', text: 'Acesso biométrico e encriptação de ponta a ponta protegem os seus dados.' },
  ],
  skip: 'Saltar',
  next: 'Seguinte',
  start: 'Começar',
  // Navigation
  navDash: 'Painel',
  navPort: 'Portfólio',
  navFor: 'Para Si',
  navProfile: 'Perfil',
  navTx: 'Movim.',
  // Dashboard
  welcomeBack: 'Bem-vindo de volta',
  greeting: 'Olá, Ricardo',
  totalValue: 'Valor Total do Portfólio',
  patPortfolioSummary: 'Resumo do Portfólio',
  dayChange: 'Hoje',
  investedLabel: 'Investido',
  returnLabel: 'Retorno',
  dailyPerf: 'Performance Diária',
  allocation: 'Alocação por Setor',
  tech: 'Tecnologia',
  energy: 'Energia',
  health: 'Saúde',
  others: 'Outros',
  assets: '12 Ativos',
  markets: 'MERCADOS',
  newsTitle: 'BCE sinaliza manutenção de taxas: o que esperar para o seu portfólio?',
  readMore: 'Ler mais em 3 min',
  insightDivTitle: '3 dividendos esta semana',
  insightDivSub: 'AAPL, MSFT e KO pagam nos próximos dias.',
  insightPlanTitle: 'Reforço automático ativo',
  insightPlanSub: '250 € serão investidos a 1 de cada mês.',
  // Portfolio
  positions: 'Posições',
  dividends: 'Dividendos',
  history: 'Histórico',
  position: 'Posição',
  units: 'Unid.',
  avgPrice: 'Preço Médio',
  detailStats: 'Estatísticas',
  detailAbout: 'Sobre',
  detailAboutName: 'Nome',
  detailAboutSector: 'Setor',
  detailAboutExchange: 'Bolsa',
  detailNoInfo: 'Sem informação disponível.',
  riskTitle: 'Análise de Risco',
  riskCta: 'Gerar análise de risco',
  riskLoading: 'A analisar fundamentais...',
  riskUnavailable: 'Análise de risco indisponível para este ativo (cobertura só para tickers dos EUA).',
  detailNoQuote: 'Cotação indisponível para este ativo.',
  open: 'Abertura',
  prevClose: 'Fecho ant.',
  dayHigh: 'Máx. dia',
  dayLow: 'Mín. dia',
  currentValue: 'Valor Atual',
  totalGain: 'Ganho Total',
  totalLoss: 'Perda Total',
  addAsset: 'Adicionar',
  buy: 'Comprar',
  sell: 'Vender',
  bsBuyTitle: 'Registar compra',
  bsSellTitle: 'Registar venda',
  bsShares: 'Nº de ações',
  bsAvgPrice: 'Preço médio (€)',
  bsDate: 'Data',
  bsTime: 'Hora',
  bsConfirm: 'Confirmar compra',
  bsSellConfirm: 'Confirmar venda',
  bsError: 'Indica o número de ações e o preço médio.',
  noPositions: 'Sem posições registadas.',
  sharesUnit: 'ações',
  sortBy: 'Ordenar por',
  sortValue: 'Valor',
  sortGainPct: 'Rentabilidade',
  sortAlpha: 'A-Z',
  sortUnits: 'Unidades',
  dividendsReceived12mo: 'Recebido (12 meses)',
  yieldLabel: 'Yield',
  upcoming: 'Próximos',
  noUpcomingDividends: 'Sem dados de dividendos futuros disponíveis.',
  received: 'Recebidos',
  noDividendsReceived: 'Sem dividendos recebidos.',
  sellAssetTitle: 'Vender ativo',
  // Profile
  investorSince: 'Investidor desde 2018',
  risk: 'Risco',
  moderate: 'Moderado',
  objective: 'Objetivo',
  retirement: 'Reforma',
  accountPlanning: 'Conta e Planeamento',
  personalData: 'Dados Pessoais',
  pdTitle: 'Dados pessoais',
  pdFirstName: 'Primeiro nome',
  pdLastName: 'Apelido',
  pdDob: 'Data de nascimento',
  pdUserId: 'ID de utilizador',
  pdEmailLabel: 'Email',
  pdLocked: 'bloqueado',
  pdEmailSaved: 'Email atualizado.',
  pdEmailError: 'Não foi possível atualizar o email.',
  impTitle: 'Importar Carteira',
  impSub: 'Carregue um ficheiro CSV ou XLSX com as suas posições.',
  impDrop: 'Arraste o ficheiro ou toque para procurar',
  impDropHint: 'CSV, XLSX · ticker, unidades, preço médio',
  impCancel: 'Cancelar',
  impConfirm: 'Importar',
  impImporting: 'A importar...',
  impToastTitle: 'Carteira importada',
  impToastSub: 'As suas posições foram atualizadas.',
  impNoFile: 'Escolhe um ficheiro CSV ou XLSX primeiro.',
  impParseError: 'Não foi possível ler o ficheiro. Verifica o formato (CSV ou XLSX).',
  exportTitle: 'Exportar Carteira',
  exportDesc: 'Exporta o histórico completo de transações e posições do teu portfólio.',
  format: 'Formato',
  exportCsv: 'CSV',
  exportPdf: 'PDF',
  period: 'Período',
  periodAllTime: 'Todo o período',
  periodThisYear: 'Este ano',
  periodLast12: 'Últimos 12 meses',
  periodCustom: 'Personalizado',
  exportStartLabel: 'Data de início',
  exportEndLabel: 'Data de fim',
  exportToastTitle: 'Exportação concluída',
  exportToastSub: 'O ficheiro foi descarregado.',
  download: 'Transferir',
  investmentPlan: 'Plano de Investimento',
  monthly: 'Mensal: € 1.200,00',
  preferences: 'Preferências',
  darkTheme: 'Tema Escuro',
  language: 'Idioma',
  langValue: 'Português (PT)',
  currency: 'Moeda Principal',
  dataManagement: 'Gestão de Dados',
  importPortfolio: 'Importar Portfólio',
  importFormats: 'CSV, XLSX, Google Sheets',
  exportReport: 'Exportar Relatório',
  annualPdf: 'Relatório Anual em PDF',
  signOut: 'Terminar Sessão',
  back: 'Voltar',
  save: 'Guardar',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
  // Profile page
  profileTitle: 'Perfil',
  memberSince: 'Membro desde 2024',
  investorProfileSection: 'Perfil de investidor',
  riskProfileLabel: 'Perfil de risco',
  horizonLabel: 'Horizonte temporal',
  horizonValue: '5–10 anos',
  sectorsLabel: 'Setores',
  sectorsValue: 'Tech, Saúde',
  investmentPlanSection: 'Plano de investimento',
  activePlan: 'Plano ativo',
  planValue: '250 €/Mensal',
  portfolioSection: 'Portfólio',
  importCsv: 'Importar Portfólio',
  importAction: 'Importar',
  exportData: 'Exportar dados',
  linkBroker: 'Ligar corretora',
  accountSection: 'Conta',
  security: 'Segurança',
  settingsLabel: 'Definições',
  longTermGoal: 'Longo prazo',
  // Settings page — notifications & delete account
  notificationsSection: 'Notificações',
  notifPriceAlerts: 'Alertas de preço',
  notifMarketNews: 'Notícias de mercado',
  notifWeeklySummary: 'Resumo semanal',
  dangerZoneSection: 'Zona de risco',
  deleteAccount: 'Eliminar conta',
  deleteAccountTitle: 'Eliminar conta',
  deleteAccountWarning: 'Esta ação é permanente e não pode ser desfeita. Todos os teus dados — perfil, posições, transações e plano de investimento — serão eliminados para sempre.',
  deleteAccountConfirmLabel: 'Para confirmar, escreve ELIMINAR abaixo.',
  deleteAccountConfirmWord: 'ELIMINAR',
  deleteAccountConfirmPh: 'Escreve ELIMINAR',
  deleteAccountButton: 'Eliminar conta permanentemente',
  deleteAccountDeleting: 'A eliminar...',
  deleteAccountError: 'Não foi possível eliminar a conta. Tenta novamente.',
  deleteAccountToastTitle: 'Conta eliminada',
  deleteAccountToastSub: 'A tua conta e todos os dados foram removidos.',
  // Net worth page
  netWorthTitle: 'Património líquido',
  totalAssets: 'Total ativos',
  liabilities: 'Passivos',
  distribution: 'Distribuição',
  investments: 'Investimentos',
  netWorthDisclaimer: 'Liquidez, imobiliário e crédito ainda não são geridos na app — o património líquido reflete só o portefólio de investimentos.',
  // Security page
  faceIdLabel: 'Face ID',
  twoFactorAuth: 'Autenticação de dois fatores',
  changePin: 'Alterar PIN',
  changePassword: 'Alterar palavra-passe',
  activeSessions: 'Sessões ativas',
  oneDevice: '1 dispositivo',
  // Add asset page
  addAssetTitle: 'Adicionar ativo',
  searchAssetPh: 'Pesquisar ativo...',
  // Settings page — import toast
  positionsUnit: 'posições',
  transactionsImportedUnit: 'transações importadas',
  // Dashboard
  timeframes: ['1S', '1M', '3M', '6M', '1A', 'Max'] as readonly string[],
  noHistoricalData: 'Sem dados históricos suficientes.',
  netWorthCardLabel: 'Património líquido',
  totalReturn: 'Retorno total',
  todayHighlights: 'Destaques do dia',
  // Perfil — riskScore
  riskScoreLabel: 'Pontuação de risco',
  riskScoreVeryConservative: 'Muito conservador',
  riskScoreConservative: 'Conservador',
  riskScoreModerate: 'Moderado',
  riskScoreAggressive: 'Agressivo',
  riskScoreVeryAggressive: 'Muito agressivo',
  riskScoreDesc: 'Calculado com base no teu perfil completo de investidor.',
  allocationLabel: 'Alocação sugerida',
  // Para Si (for-you)
  forYouTitle: 'Para Si',
  recLoading: 'A gerar recomendações...',
  recEmpty: 'Sem recomendações disponíveis de momento.',
  recCompleteProfile: 'Completa o teu perfil de investidor para receberes recomendações personalizadas.',
  recNew: 'Nova compra',
  recReinforce: 'Reforço',
  recPerMonth: '/mês',
  recScore: 'Score',
  recPaceAlert: 'O ritmo atual pode não ser suficiente para atingir o teu objetivo. Considera aumentar o plano mensal.',
  recMonthlyPlan: 'Plano mensal',
  recSectionTitle: 'Recomendado para ti',
  recSectionSub: 'Com base no teu perfil e carteira atual',
  recInvestNow: 'Investir agora',
};
