export const pt = {
  appName: 'Portify',
  tagline: 'Gestão de património inteligente e simplificada.',
  // Auth
  loginTitle: 'Bem-vindo de volta',
  loginSubtitle: 'Inicie sessão para gerir o seu património.',
  emailLabel: 'Email',
  emailPh: 'nome@exemplo.com',
  passwordLabel: 'Palavra-passe',
  passwordPh: '••••••••',
  forgotPassword: 'Esqueceu-se da palavra-passe?',
  signIn: 'Entrar',
  faceId: 'Entrar com Face ID',
  noAccount: 'Não tem conta?',
  createAccount: 'Criar conta',
  rememberMe: 'Manter sessão iniciada',
  orContinue: 'ou continue com',
  // Register
  registerTitle: 'Criar a sua conta',
  registerSubtitle: 'Comece a investir em poucos minutos.',
  regFirstName: 'Primeiro Nome',
  regLastName: 'Sobrenome',
  firstNamePh: 'Ricardo',
  lastNamePh: 'Ferreira',
  regDob: 'Data de Nascimento',
  regDobPh: 'DD / MM / AAAA',
  regUserId: 'ID de Utilizador',
  regUserIdPh: '@ricardo.f',
  confirmPasswordLabel: 'Confirmar palavra-passe',
  acceptTerms: 'Aceito os',
  terms: 'Termos',
  and: 'e a',
  privacy: 'Política de Privacidade',
  haveAccount: 'Já tem conta?',
  // PIN
  pinTitle: 'Introduza o PIN',
  pinSub: 'Use o código de 6 dígitos para entrar',
  forgotPin: 'Esqueci o PIN',
  // Onboarding
  onbSteps: [
    { icon: 'monitoring', title: 'Todo o seu património num só lugar', text: 'Acompanhe ações, ETFs e cripto com dados de mercado em tempo real.' },
    { icon: 'donut_small', title: 'Decisões com clareza', text: 'Visualize a alocação por setor e a performance com gráficos simples e precisos.' },
    { icon: 'lock', title: 'Seguro e privado', text: 'Acesso biométrico e encriptação de ponta a ponta protegem os seus dados.' },
  ],
  skip: 'Saltar',
  next: 'Seguinte',
  start: 'Começar',
  // Navigation
  navDash: 'Painel',
  navPort: 'Portfólio',
  navFor: 'Para Si',
  navProfile: 'Perfil',
  navTx: 'Movim.',
  // Dashboard
  greeting: 'Olá, Ricardo',
  totalValue: 'Valor Total do Portfólio',
  dailyPerf: 'Performance Diária',
  allocation: 'Alocação por Setor',
  tech: 'Tecnologia',
  energy: 'Energia',
  health: 'Saúde',
  others: 'Outros',
  assets: '12 Ativos',
  markets: 'MERCADOS',
  newsTitle: 'BCE sinaliza manutenção de taxas: o que esperar para o seu portfólio?',
  readMore: 'Ler mais em 3 min',
  // Portfolio
  positions: 'Posições',
  dividends: 'Dividendos',
  history: 'Histórico',
  position: 'Posição',
  units: 'Unid.',
  avgPrice: 'Preço Médio',
  currentValue: 'Valor Atual',
  totalGain: 'Ganho Total',
  totalLoss: 'Perda Total',
  addAsset: 'Adicionar',
  buy: 'Comprar',
  sell: 'Vender',
  // Profile
  investorSince: 'Investidor desde 2018',
  risk: 'Risco',
  moderate: 'Moderado',
  objective: 'Objetivo',
  retirement: 'Reforma',
  accountPlanning: 'Conta e Planeamento',
  personalData: 'Dados Pessoais',
  investmentPlan: 'Plano de Investimento',
  monthly: 'Mensal: € 1.200,00',
  preferences: 'Preferências',
  darkTheme: 'Tema Escuro',
  language: 'Idioma',
  langValue: 'Português (PT)',
  currency: 'Moeda Principal',
  dataManagement: 'Gestão de Dados',
  importPortfolio: 'Importar Portfólio',
  importFormats: 'CSV, XLSX, Google Sheets',
  exportReport: 'Exportar Relatório',
  annualPdf: 'Relatório Anual em PDF',
  signOut: 'Terminar Sessão',
  back: 'Voltar',
  save: 'Guardar',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
};
